version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techwithmolato-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./mounted-volume:/techwithmolato/mounted-volume
